### ISSUE TITLE
APRS Longitude not showing 

### ISSUE THREAD

**Issue by currentusername** [mikaelnousiainen/RS41ng#33]
My longitude is 150 00'00" and does not show up on my FT3D is that because $lon is up to 6 characters and my longitude has more characters?

**Comment by currentusername** [comment]
Just tried $lat $lon in the APRS comment and they both appear there to 6 characters, but in the APRS telemetry data part of the message it only shows the latitude.

**Comment by mikaelnousiainen** [comment]
Thanks for reporting this. I'll have a look at the issue soon.

**Comment by neilogd** [comment]
Seeing similar too, direwolf output in case it's of use:

VK2GPU-11 audio level = 16(10/10)   [NONE]   ___|||___
[0.4] VK2GPU-11>APZ41N,WIDE1-1,WIDE2-1:!3343.56S/105233.207WO086/000/A=000583/P3S6T37V3956C00 Bat: 3956 mV, Sats: 6,  RS41ng FOX
Unexpected character "3" found where period expected in longitude.
Position, TBD, Experimental
S 33 43.5600, Invalid Longitude, alt 583 ft
WO086/000/P3S6T37V3956C00 Bat: 3956 mV, Sats: 6,  RS41ng FOX

**Comment by mikaelnousiainen** [comment]
@currentusername @neilogd It's been a long time, but I finally think I figured out what the issue was. The code (that I copied over from some older RS41 firmware codebase) was using 8-bit signed values for degrees, so of course it did not support longitudes > 128 or < -127. Now this should be fixed in the codebase, please give it a try!

**Comment by currentusername** [comment]
Just tried it out and it works! Thank you!

**Comment by mikaelnousiainen** [comment]
Great, thanks for testing, closing the issue now.
